[package]
name = "ascii-example"
version = "0.1.0"
authors = ["Elijah Seed Arita <bananatrooper52@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.17.5"